"use client";

import Image from "next/image";
import { useState } from "react";
import { ChevronRight, Clipboard, Download, Expand, Eye, Layers3, Palette, RefreshCw, SlidersHorizontal, Sparkles, WandSparkles } from "lucide-react";

const concepts = [
  ["Concept #1", "Modern Fast-Casual Taproom & Kitchen", "High-margin chef-driven fast casual concept designed to capture significant unfulfilled lunch and dinner spending from 58,000...", "$195 / SF", "5 Perspectives"],
  ["Concept #2", "Architectural Reformer Pilates Studio", "Serene high-end Pilates studio equipped with 16 custom wood-frame reformers, backlit architectural mirrors,...", "$165 / SF", "4 Perspectives"],
  ["Concept #3", "Longevity & Regenerative Recovery Clinic", "Next-generation proactive health sanctuary providing whole-body cryotherapy, private infrared sauna suites, hyperbaric oxygen chambers, and biomarker IV lounges....", "$220 / SF", "3 Perspectives"],
];

const angles = [
  ["Front-of-House Core", "Main Dining & POS Counter", "24mm f/2.8 Architectural Tilt-Shift"],
  ["Exterior Facade & Patio", "Storefront & Sidewalk Patio", "35mm f/2.0 Eye-Level Exterior"],
  ["Back-of-House MEP", "Commercial Kitchen & Type I Hood", "28mm f/4.0 Technical Architectural"],
  ["Nightlife & Bar Lighting", "Evening Ambient Lounge", "50mm f/1.8 Low-Light Cinematic"],
  ["Material Craft Study", "Architectural Millwork & Finishes", "85mm f/2.8 Macro Architectural Vignette"],
];

const ledger = [
  ["Ceiling & Lighting Grid", "14.5ft bare metal deck with decommissioned fluorescent troffers & exposed conduit", "Matte black acoustic baffle field with 3-circuit dimmable 2700K architectural LED track spotlights", "Electrical & Lighting ($31,000)"],
  ["Floor Slab & Finishes", "Raw scarred concrete slab with adhesive residue from prior retail tenant", "Diamond-ground seamless honed terrazzo with polished brass movement joint dividing strips", "Finishes & Flooring ($32,000)"],
  ["Service Counter & Bar Island", "Open vacancy without demarcated order or checkout infrastructure", "24-foot radius fluted white oak POS island with integrated POS terminals and dual ADA transaction counter", "Custom Millwork ($52,000)"],
  ["MEP & Kitchen Infrastructure", "Sanitary drain stubbed to demising wall; no exhaust or grease separation", "Core drilled waste lines tied into 1,500-gal exterior trap + 14ft Type 1 stainless exhaust hood chase", "Plumbing & Kitchen Infrastructure ($88,000)"],
  ["Storefront Facade", "Fixed single-glazed commercial aluminum plate storefront", "Bi-folding thermally-broken aluminum glass curtain wall opening to sidewalk outdoor patio seating", "Storefront Facade ($24,000)"],
];

const materials = [
  ["#FFF0F0", "Honed Venetian Terrazzo", "4mm Carrara marble aggregate, seamless matte resin binder, Class 1 slip resistance", "Heavy Commercial Foot Traffic (10+ Year Lifespan)"],
  ["#FFFCEF", "Fluted American White Oak", "Solid 1.5\" radius fluted profiles, low-VOC ultra-matte clear polyurethane finish", "Commercial Architectural Millwork"],
  ["#EDFCFC", "Calacatta Quartzite Counter", "3cm engineered quartzite, honed anti-microbial surface with eased pencil edge", "Food-grade NSF Certified"],
  ["#151D30", "Architectural Jet Black Steel", "RAL 9005 fine textured powdercoat on structural hollow steel sections", "AAMA 2604 Compliant Exterior/Interior"],
  ["#E97700", "Acoustic Wood Slat Ceiling", "FSC Certified white oak veneers over recycled PET charcoal sound-absorbing felt", "NRC 0.85 Sound Absorption, ASTM E84 Class A Fire"],
];

export default function ProjectRenderingsPanel() {
  const [activeConcept, setActiveConcept] = useState(0);
  const [activeAngle, setActiveAngle] = useState(0);
  const [mode, setMode] = useState<"Slider" | "Side-by-Side" | "Fade" | "AI Only">("Slider");
  const [split, setSplit] = useState(50);
  const [copied, setCopied] = useState(false);
  const prompt = "Photorealistic interior conversion of vacant commercial retail suite, 14.5ft exposed concrete deck with matte black acoustic spray, fluted white oak POS island with honed Calacatta quartzite countertops, continuous honed Italian terrazzo flooring with inlaid brass expansion joints, custom banquette seating in cognac full-grain leather, suspended 2700K warm architectural track lighting, lush fiddle leaf ficus planters, soft indirect cove lighting.";
  const copyPrompt = async () => { await navigator.clipboard?.writeText(prompt); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };

  return <section className="bg-[#F5F8FB] p-3 sm:p-4 lg:p-6">
    <section className="overflow-hidden rounded-[4px] border border-[#CBD7E6] bg-white">
      <header className="border-b border-[#DCE5EF] px-4 py-4">
        <div className="flex flex-wrap items-center gap-3 text-[10px]"><span className="rounded bg-[#E9FFF2] px-2 py-1 text-[#00A550]"><Sparkles className="mr-1 inline h-3 w-3" />AI Spatial Intelligence Engine</span><span className="text-[#65758C]">3 Architectural Concept Dossiers</span></div>
        <h2 className="mt-3 text-[16px] font-bold text-[#151D30]">Photorealistic AI Tenant Visualizations</h2>
        <p className="mt-1 max-w-6xl text-[11px] leading-4 text-[#65758C]">Explore how this vacant commercial footprint converts into top recommended business concepts. Select a concept below to inspect multi-angle 4K transformations, construction MEP overlays, and architectural material specs.</p>
        <div className="mt-3 flex gap-3"><Button primary icon={<WandSparkles />}>AI Rendering Studio</Button><Button icon={<Download />}>Download 4K</Button></div>
      </header>
      <div className="grid gap-3 p-3 lg:grid-cols-3">{concepts.map((concept, index) => <button type="button" key={concept[0]} onClick={() => setActiveConcept(index)} className={`rounded-[5px] border p-3 text-left transition ${activeConcept === index ? "border-2 border-[#2861E7] bg-white" : "border-[#CBD7E6] bg-[#FBFCFE] hover:border-[#93B5EE]"}`}><div className="flex justify-between text-[9px]"><span className={`rounded px-1.5 py-0.5 font-semibold ${index === 0 ? "bg-[#E9FFF2] text-[#00A550]" : "bg-[#EDF2F8] text-[#64758D]"}`}>{concept[0]}</span><span className="text-[#65758C]">Fit Score: <b className="text-[#00A550]">{index === 2 ? "76" : "91"} /100</b></span></div><h3 className="mt-3 text-[15px] font-bold text-[#151D30]">{concept[1]}</h3><p className="mt-2 h-9 overflow-hidden text-[11px] leading-[14px] text-[#65758C]">{concept[2]}</p><div className="mt-3 flex justify-between border-t border-[#DCE5EF] pt-3 text-[10px]"><span className="rounded bg-[#EEF4FA] px-1.5 py-0.5 font-semibold text-[#526174]">{concept[3]}</span><span className="inline-flex items-center text-[#65758C]">{concept[4]} <ChevronRight className="ml-1 h-3 w-3" /></span></div></button>)}</div>
    </section>

    <section className="mt-4 rounded-[4px] border border-[#DCE5EF] bg-white p-3">
      <div className="flex flex-col justify-between gap-3 border-b border-[#DCE5EF] pb-3 md:flex-row md:items-end"><div><div className="text-[10px]"><span className="rounded bg-[#E9FFF2] px-2 py-1 text-[#00A550]">★ #1 Recommended Tenant Match</span><span className="ml-2 text-[#65758C]">· Front-of-House Core</span></div><h2 className="mt-3 text-[16px] font-bold text-[#151D30]">{angles[activeAngle][1]}</h2><p className="mt-1 text-[11px] text-[#65758C]">Wide-angle interior perspective highlighting the custom fluted oak ordering counter, customer circulation, and 46-seat dining room.</p></div><div className="flex gap-3"><Button primary icon={<Clipboard />} onClick={copyPrompt}>{copied ? "Copied" : "Copy Prompt"}</Button><Button icon={<Expand />}>Full Screen</Button></div></div>
      <div className="mt-4 overflow-hidden rounded-[4px] border border-[#CBD7E6]"><div className="flex flex-col justify-between gap-3 border-b border-[#DCE5EF] p-3 lg:flex-row lg:items-center"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#E9FFF2] text-[#00A550]"><Sparkles className="h-4 w-4" /></span><span><b className="block text-[11px]">Modern Fast-Casual Taproom & Kitchen · {angles[activeAngle][1]}</b><small className="text-[9px] text-[#65758C]">Warm Coastal Mediterranean with Terrazzo & Fluted Oak</small></span></div><div className="flex flex-wrap gap-2">{(["Slider", "Side-by-Side", "Fade", "AI Only"] as const).map(item=><button type="button" onClick={() => setMode(item)} key={item} className={`inline-flex h-8 items-center gap-1 px-3 text-[10px] ${mode === item ? "rounded bg-[#2861E7] text-white" : "border border-[#E3EAF3] text-[#526174]"}`}>{item === "Slider" ? <SlidersHorizontal className="h-3 w-3" /> : item === "AI Only" ? <Eye className="h-3 w-3" /> : <Layers3 className="h-3 w-3" />}{item}</button>)}<Button icon={<RefreshCw />}>Regenerate</Button></div></div>
        <Comparison mode={mode} split={split} onSplit={setSplit} />
        <div className="flex flex-wrap items-center justify-between gap-2 border-t border-[#DCE5EF] px-3 py-2 text-[10px]"><span><b className="text-[#526174]">⚖ Conceptual Architectural AI Visualization.</b> <span className="text-[#65758C]">For spatial feasibility, lease marketing & cost planning.</span></span><span className="rounded bg-[#EEF4FA] px-2 py-1 text-[#65758C]">Tier: Premium Boutique ($195 / SF)</span></div>
      </div>
    </section>

    <section className="mt-4 rounded-[4px] border border-[#CBD7E6] bg-white"><header className="flex items-center justify-between border-b border-[#DCE5EF] px-4 py-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#E9FFF2] text-[#00A550]">▣</span><h2 className="text-[13px] font-bold">Architectural Angles for Modern Fast-Casual Taproom & Kitchen</h2></div><small className="hidden text-[9px] text-[#65758C] md:block">Click any perspective to load in interactive comparison</small></header><div className="grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-5">{angles.map((angle,index)=><button type="button" key={angle[0]} onClick={() => setActiveAngle(index)} className={`overflow-hidden rounded-[8px] border text-left ${index===activeAngle?"border-2 border-[#2861E7]":"border-[#CBD7E6]"}`}><div className="relative h-[135px]"><Image src="/assets/images/taproom-interior.png" alt={angle[1]} fill className="object-cover" sizes="240px"/><span className="absolute right-1 top-1 rounded bg-[#151D30]/85 px-1.5 py-0.5 text-[9px] text-white">{angle[0]}</span></div><div className="p-2"><b className="block truncate text-[12px] text-[#151D30]">{angle[1]}</b><small className="mt-1 block truncate text-[9px] text-[#65758C]">{angle[2]}</small></div></button>)}</div></section>

    <section className="mt-4 overflow-hidden rounded-[4px] border border-[#BFE9D0] bg-[#F2FFF7]"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[#C9ECD7] px-4 py-3"><div className="flex items-center gap-3"><Layers3 className="h-5 w-5 text-[#00A550]"/><span><h2 className="text-[13px] font-bold">Spatial Conversion & MEP Transformation Analysis</h2><p className="mt-1 text-[9px] text-[#65758C]">How the raw commercial retail shell is structurally and visually converted to meet code and operational requirements.</p></span></div><b className="rounded-full bg-[#D7E2F2] px-4 py-2 text-[11px]">Property Area: 2,450 RSF</b></header><div className="m-3 overflow-x-auto border border-[#CAD6E4] bg-white"><h3 className="p-4 text-[16px] font-semibold">Credit Consumption Ledger</h3><table className="min-w-[960px] w-full text-left text-[10px]"><thead className="bg-[#E2E8F1] text-[#4E5D71]"><tr>{["BUILDING COMPONENT", "RAW SHELL / CURRENT CONDITION", "AI ARCHITECTURAL TRANSFORMATION", "CAPEX MAPPING"].map(x=><th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{ledger.map(row=><tr key={row[0]} className="border-t border-[#DCE5EF]"><td className="px-4 py-4 font-medium">{row[0]}</td><td className="px-4 py-4">❌{row[1]}</td><td className="px-4 py-4">✅ {row[2]}</td><td className="px-4 py-4 whitespace-nowrap text-[#00A550]">{row[3]}</td></tr>)}</tbody></table></div></section>

    <section className="mt-4 rounded-[4px] border border-[#CBD7E6] bg-white"><header className="flex items-center gap-3 border-b border-[#DCE5EF] px-4 py-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#E9FFF2] text-[#00A550]"><Palette className="h-4 w-4" /></span><div><h2 className="text-[13px] font-bold">Architectural Materials & Finishes Specification Board</h2><p className="mt-1 text-[9px] text-[#65758C]">Commercial-grade materials synthesized in the AI rendering, calibrated to meet code compliance and traffic durability.</p><p className="mt-2 text-[9px] text-[#65758C]">Style: <b className="text-[#526174]">Warm Coastal Mediterranean with Terrazzo & Fluted Oak</b></p></div></header><div className="grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-4">{materials.map(item=><article key={item[1]} className="rounded-[8px] border border-[#CBD7E6] bg-[#F8FAFC] p-3"><div className="flex justify-between"><i className="h-8 w-8 rounded" style={{background:item[0]}}/><span className="rounded border border-[#AFC3DF] px-1 py-0.5 text-[9px] text-[#2861E7]">$$$</span></div><h3 className="mt-3 text-[12px] font-bold">{item[1]}</h3><p className="mt-2 min-h-[42px] text-[10px] leading-[13px] text-[#65758C]">{item[2]}</p><p className="mt-2 border-t border-[#D6E0EB] pt-2 text-[10px] text-[#00A550]">Rating:<br />{item[3]}</p></article>)}</div></section>

    <section className="mt-4 rounded-[4px] border border-[#CBD7E6] bg-[#EEF3F9]"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[#D6E0EB] px-4 py-3"><span className="inline-flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#E9FFF2] text-[#00A550]"><Sparkles className="h-4 w-4" /></span><b className="text-[13px]">VisionSpatial Neural Diffusion Architecture Parameters</b></span><small className="text-[9px] text-[#65758C]">Engine: VisionSpatial Neural Diffusion v4.2 Pro　 ·　 Res: 3840 x 2160 (4K UHD Architectural Spec)</small></header><div className="p-3"><div className="flex justify-between"><h2 className="text-[13px] font-bold">Synthesized Spatial Prompt:</h2><Button icon={<Clipboard />} onClick={copyPrompt}>{copied ? "Copied" : "Copy Prompt"}</Button></div><p className="mt-3 rounded border border-[#8FA4BF] bg-white p-3 text-[11px] leading-[14px] text-[#8AA0BC]">{prompt}</p><footer className="mt-3 grid gap-2 text-[10px] text-[#526174] sm:grid-cols-3"><span>Target Opening Timeline: <b className="text-[#151D30]">14 - 18 Weeks</b></span><span>Estimated Tenant Net CapEx: <b className="text-[#151D30]">$341,750</b></span><span>Landlord TI Contribution: <b className="text-[#151D30]">$110,250 ($45/SF TI)</b></span></footer></div></section>
  </section>;
}

function Comparison({ mode, split, onSplit }: { mode: "Slider" | "Side-by-Side" | "Fade" | "AI Only"; split: number; onSplit: (value: number) => void }) {
  if (mode === "AI Only") return <div className="relative h-[460px]"><Image src="/assets/images/taproom-interior.png" alt="AI transformed fast casual taproom" fill className="object-cover" sizes="100vw"/><Badge label="AI TRANSFORMED: MODERN FAST - CASUAL TAPROOM & KITCHEN" side="right" /></div>;
  if (mode === "Side-by-Side") return <div className="grid h-[460px] grid-cols-2"><div className="relative"><Image src="/assets/images/raw-vacancy.png" alt="Current raw vacancy" fill className="object-cover" sizes="50vw"/><Badge label="CURRENT RAW VACANCY" side="left" /></div><div className="relative"><Image src="/assets/images/taproom-interior.png" alt="AI transformed taproom" fill className="object-cover" sizes="50vw"/><Badge label="AI TRANSFORMED: MODERN FAST - CASUAL TAPROOM & KITCHEN" side="right" /></div></div>;
  return <div className="relative h-[460px] overflow-hidden"><Image src="/assets/images/raw-vacancy.png" alt="Current raw vacancy" fill className="object-cover" sizes="100vw"/><div className="absolute inset-y-0 right-0 overflow-hidden" style={{width:`${100-split}%`}}><div className="relative h-full" style={{width:`${10000/(100-split)}%`}}><Image src="/assets/images/taproom-interior.png" alt="AI transformed taproom" fill className={`object-cover ${mode === "Fade" ? "opacity-70" : ""}`} sizes="100vw"/><Badge label="AI TRANSFORMED: MODERN FAST - CASUAL TAPROOM & KITCHEN" side="right" /></div></div><Badge label="CURRENT RAW VACANCY" side="left" /><input aria-label="Image comparison split" type="range" min="10" max="90" value={split} onChange={event=>onSplit(Number(event.target.value))} className="absolute bottom-3 left-1/2 z-10 h-2 w-48 -translate-x-1/2 accent-[#2861E7]"/><div className="absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full bg-[#EAF0F7] px-4 py-2 text-[11px] font-semibold">{100-split}% Concept / {split}% Original</div></div>;
}
function Badge({label,side}:{label:string;side:"left"|"right"}) { return <span className={`absolute top-4 rounded-full px-5 py-3 text-[11px] text-white ${side === "left" ? "left-3 bg-[#151D30]" : "right-3 bg-[#2861E7]"}`}>{label}</span> }
function Button({children,icon,primary=false,onClick}:{children:React.ReactNode;icon:React.ReactNode;primary?:boolean;onClick?:()=>void}) { return <button type="button" onClick={onClick} className={`inline-flex h-10 items-center gap-2 px-4 text-[11px] font-medium ${primary ? "bg-[#2861E7] text-white hover:bg-[#1F53CC]" : "bg-[#F2F5F9] text-[#27364B] hover:bg-[#E8EEF5]"}`}><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>{children}</button> }
