"use client";

import { Compass, MapPin, Search } from "lucide-react";
import { useState } from "react";

const stats = [
  ["Total Population", "14,280", "+2.8% Annual", "green"],
  ["Median Household Income", "$118,500", "Top 8% in Metropolitan Area", "blue"],
  ["Daytime Population", "22,400", "Corporate Employees + Commuters", "dark"],
  ["Annual Retail Expenditure", "$48.5M / yr", "Unfulfilled Outflow Demand", "green"],
];
const spending = [
  ["Food & Dining Away from Home", "Index 164", "$14.2M", "blue", "26%"],
  ["Boutique Fitness & Athletic Services", "Index 152", "$4.8M", "green", "23%"],
  ["Personal Care & Longevity Wellness", "Index 148", "$3.6M", "orange", "20%"],
];

export function MarketPanel() {
  const [radius, setRadius] = useState("0.5 Mile");
  return <section className="m-3 overflow-hidden rounded-[4px] border border-[#CBD7E6] bg-white sm:m-4 lg:m-6">
    <PanelHeader title="Trade Area Demographics & Consumer Demand" subtitle="Verified demographic rings and retail consumer spending expenditure models from Esri ArcGIS & ACS." extra={<RadiusPicker value={radius} onChange={setRadius} />} />
    <div className="p-3"><Stats /><div className="mt-3 rounded-[5px] bg-[#F0F4F8] p-3"><div className="flex flex-wrap justify-between gap-2"><h3 className="text-[13px] font-bold">Trade Area Consumer Spending Indices (National Baseline = 100)</h3><span className="text-[10px] text-[#00A550]">Indexed Above National Average</span></div><div className="mt-3 grid gap-3 lg:grid-cols-3">{spending.map(item => <SpendingCard key={item[0]} item={item} />)}</div></div><div className="mt-3 grid gap-3 lg:grid-cols-3"><MarketInsight label="Commercial Retail Vacancy:" value="3.4%" note="Extremely tight submarket supply with low tenant concessions." /><MarketInsight label="Average Submarket Asking Rent:" value="$48.50 / SF" note="This space at $44/SF is competitively positioned." /><MarketInsight label="Daily Traffic & Visibility:" value="18,500 daily vehicles" note="Rapid Luxury Infill & High Density" blue /></div></div>
  </section>;
}

export function CompetitionPanel() {
  const [radius, setRadius] = useState("0.5 Mile");
  const [view, setView] = useState<"Interactive Map" | "List View">("Interactive Map");
  return <section className="m-3 overflow-hidden rounded-[4px] border border-[#CBD7E6] bg-white sm:m-4 lg:m-6">
    <PanelHeader title="Trade Area Competition & Synergies" subtitle="Spatial mapping of direct, indirect, and complementary retail operators." extra={<div className="flex gap-2"><select aria-label="Establishment type" className="h-6 border border-[#CBD7E6] bg-white px-2 text-[9px]"><option>All Establishment</option></select><div className="inline-flex border border-[#CBD7E6] p-0.5 text-[9px]"><button type="button" onClick={() => setView("Interactive Map")} className={`px-2 ${view === "Interactive Map" ? "bg-[#2861E7] text-white" : "text-[#526174]"}`}>Interactive Map</button><button type="button" onClick={() => setView("List View")} className={`px-2 ${view === "List View" ? "bg-[#2861E7] text-white" : "text-[#526174]"}`}>List View</button></div></div>} />
    <div className="p-3"><Stats /><div className="mt-3 overflow-hidden rounded-[4px] border border-[#D6E0EB]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#DCE5EF] px-2 py-2"><RadiusPicker value={radius} onChange={setRadius} /><label className="relative"><Search className="absolute left-2 top-1/2 h-3 w-3 -translate-y-1/2 text-[#7B8A9D]" /><input type="search" aria-label="Search establishments" placeholder="Search by property address, name or city..." className="h-6 w-[255px] border border-[#CBD7E6] pl-6 pr-2 text-[9px]" /></label></div>{view === "Interactive Map" ? <TradeMap /> : <CompetitorList />}</div></div>
  </section>;
}

function PanelHeader({ title, subtitle, extra }: { title: string; subtitle: string; extra: React.ReactNode }) { return <header className="flex flex-col justify-between gap-3 border-b border-[#DCE5EF] px-3 py-3 sm:flex-row sm:items-center"><div><h2 className="text-[14px] font-bold text-[#151D30]">{title}</h2><p className="mt-1 text-[10px] text-[#65758C]">{subtitle}</p></div>{extra}</header>; }
function RadiusPicker({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <div className="inline-flex items-center gap-1 rounded border border-[#D6E0EB] px-1 py-1 text-[9px]"><span className="px-1 text-[#526174]">Radius Ring:</span>{["0.5 Mile", "1 Mile", "3 Mile", "5 Mile"].map(item => <button type="button" onClick={() => onChange(item)} key={item} className={`rounded px-2 py-1 ${value === item ? "bg-[#2861E7] text-white" : "text-[#526174] hover:bg-[#EEF3F8]"}`}>{item}</button>)}</div>; }
function Stats() { return <div className="grid gap-3 lg:grid-cols-4">{stats.map(([label, value, note, color]) => <article key={label} className="rounded-[5px] border border-[#CBD7E6] p-3"><p className="text-[9px] text-[#65758C]">{label}</p><b className={`mt-2 block text-[16px] ${color === "green" ? "text-[#00A550]" : color === "blue" ? "text-[#2861E7]" : "text-[#151D30]"}`}>{value}</b><p className={`mt-2 border-t border-[#DCE5EF] pt-2 text-[8px] font-medium ${color === "green" ? "text-[#00A550]" : "text-[#526174]"}`}>{note}</p></article>)}</div>; }
function SpendingCard({ item }: { item: string[] }) { const [label, index, annual, color, percent] = item; const accent = color === "blue" ? "#2861E7" : color === "green" ? "#00A550" : "#EE9700"; return <article className="rounded-[5px] border-2 bg-white p-3" style={{ borderColor: accent }}><div className="flex justify-between gap-2 text-[10px] font-bold"><span>{label}</span><span style={{ color: accent }}>{index}</span></div><div className="mt-3 h-2 rounded-full bg-[#E6EDF5]"><div className="h-full rounded-full" style={{ width: percent, backgroundColor: accent }} /></div><p className="mt-3 text-[9px] text-[#65758C]">Annual Spend in Ring: <b className="float-right rounded bg-[#EDF3FA] px-1.5" style={{ color: accent }}>{annual}</b></p></article>; }
function MarketInsight({ label, value, note, blue = false }: { label: string; value: string; note: string; blue?: boolean }) { return <article className="rounded-[5px] border border-[#E0E7F0] bg-[#FBFCFE] p-3"><p className="text-[9px] text-[#65758C]">{label}</p><b className={`mt-2 block text-[15px] ${blue ? "text-[#2861E7]" : "text-[#151D30]"}`}>{value}</b><p className="mt-2 border-t border-[#DCE5EF] pt-2 text-[9px] text-[#65758C]">{note}</p></article>; }
function TradeMap() { const pins = [["left-[20%] top-[47%]","#2861E7"],["left-[37%] top-[24%]","#2861E7"],["left-[44%] top-[35%]","#00A550"],["left-[56%] top-[29%]","#EE8300"],["left-[60%] top-[51%]","#7956B8"],["left-[74%] top-[50%]","#2861E7"],["left-[47%] top-[72%]","#7956B8"],["left-[59%] top-[64%]","#00A550"]]; return <div className="relative h-[370px] overflow-hidden bg-[#D9E7CE] [background-image:linear-gradient(32deg,transparent_47%,#fff9_48%,transparent_49%),linear-gradient(108deg,transparent_46%,#eabf7880_47%,transparent_48%),linear-gradient(0deg,transparent_48%,#f7edcd_49%,transparent_51%)] [background-size:130px_100px,190px_130px,90px_70px]"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(90deg,transparent_49%,#fff8_50%,transparent_51%),linear-gradient(0deg,transparent_49%,#fff8_50%,transparent_51%)] [background-size:60px_60px]"/><span className="absolute left-4 top-3 grid h-9 w-9 place-items-center rounded-full bg-white text-[#27364B] shadow"><Compass className="h-5 w-5" /></span>{pins.map(([position,color],index) => <i key={index} className={`absolute ${position} h-4 w-4 rounded-full border-4 border-white shadow`} style={{ backgroundColor: color }} />)}<span className="absolute left-[52%] top-[43%] grid h-9 w-9 place-items-center rounded-full bg-[#EF3340] text-white shadow">★</span><small className="absolute left-[48%] top-[53%] rounded bg-[#EF3340] px-1.5 py-1 text-white">Selected Property</small><b className="absolute bottom-8 left-[6%] text-[16px]">Fort Worth</b><b className="absolute bottom-[28%] left-[51%] text-[16px]">Dallas</b><div className="absolute bottom-4 right-4 grid overflow-hidden rounded bg-white shadow"><button className="px-3 py-2 text-[18px]">+</button><button className="border-t px-3 py-2 text-[18px]">−</button></div></div>; }
function CompetitorList() { return <div className="grid gap-2 p-3 text-[10px]">{["Kerbey Lane Cafe", "Neighborhood Coffee", "East Austin Athletic Club", "Juiceland", "Whole Foods Market"].map((name,index) => <div key={name} className="flex items-center justify-between rounded border border-[#DCE5EF] px-3 py-3"><span><MapPin className="mr-2 inline h-3 w-3 text-[#2861E7]" />{name}</span><span className="text-[#00A550]">{0.2 + index / 10} mi · Complementary</span></div>)}</div>; }
