import Image from "next/image";
import { AlertTriangle, CheckCircle2, Expand } from "lucide-react";

export function OverviewPanel() {
  return <div className="grid gap-3 p-3 sm:p-4 lg:grid-cols-[minmax(0,1.42fr)_minmax(340px,1fr)]">
    <div className="space-y-3"><Panel><span className="rounded bg-[#EAFBF1] px-2 py-1 text-[9px] text-[#00A550]">★ #1 Recommended Archetype (91/100 Fit)</span><span className="ml-3 text-[9px] text-[#526174]">Food & Beverage</span><h2 className="mt-3 text-[14px] font-bold">Fast Casual Taproom & Kitchen</h2><p className="mt-1 text-[10px] leading-[15px] text-[#65758C]">Second-gen retail shell with existing 400A power and high ceilings, ideal for fast-casual craft beer and elevated counter service.</p><div className="mt-3 rounded bg-[#F0F5FA] p-3"><b className="text-[10px] text-[#2861E7]">Target Demographic Alignment:</b><p className="mt-1 text-[9px] text-[#65758C]">Affluent tech & creative professionals ages 24-46 seeking fresh dine-in and takeout.</p></div><div className="mt-2 grid grid-cols-4 gap-2 text-center">{[["Fit Score","91 /100"],["Est. CapEx / SF","91 /100"],["Landlord TI","$45/SF"],["Payback ROI","14.2 Mo"]].map(([label,value]) => <div key={label} className="rounded bg-[#F4F7FA] py-2"><p className="text-[8px] text-[#728096]">{label}</p><b className="text-[10px] text-[#00A550]">{value}</b></div>)}</div><div className="mt-3 flex justify-between border-t pt-2 text-[9px] text-[#65758C]"><span>Timeline to Opening: <b className="text-[#27364B]">14 - 18 Weeks</b></span><span>Report Status: <b className="text-[#27364B]">100% Ready</b></span></div></Panel>
    <Infrastructure /><div className="grid gap-3 md:grid-cols-2"><Checklist title="Core Conversion Strengths" tone="green" items={["Existing Grease Trap & Utility Drops: Saves an estimated $68,000 in heavy subterranean civil plumbing.","High Daytime Spending Index: 1-mile radius captures $142.8M in annual retail & dining outflow.","Optimal Floor Footprint: 2,450 SF allows 68 interior seats plus 24-seat front patio conversion."]}/><Checklist title="Identified Commercial Risks & Mitigations" tone="orange" items={["Peak Hour Parking Pressure: Recommend partnering with adjacent garage for validated merchant parking.","Austin Health Permit Backlog: Plan review currently averages 10 weeks; early submittal is essential.","HVAC Return Ducting: May require 2 additional drop diffusers to balance kitchen heat load."]}/></div></div>
    <div className="relative min-h-[350px] overflow-hidden border border-[#D7E0EB] bg-[#1C2731]"><Image src="/assets/images/taproom-interior.png" alt="Modern fast casual taproom interior" fill className="object-cover" sizes="(min-width: 1024px) 38vw, 100vw" /><button className="absolute left-3 top-3 inline-flex items-center gap-1 border border-white/60 bg-black/35 px-3 py-2 text-[10px] text-white"><Expand className="h-3 w-3" />Full Preview</button></div>
  </div>;
}

function Panel({children}:{children:React.ReactNode}) { return <section className="rounded-[5px] border border-[#D7E0EB] bg-white p-3 text-[#151D30]">{children}</section> }
function Infrastructure(){ return <Panel><h3 className="text-[13px] font-bold">Physical Infrastructure & MEP Feasibility Audit</h3><div className="mt-3 grid gap-2 md:grid-cols-3">{[["Electrical Service: 400A 3-Phase","Sufficient electrical panel capacity for heavy commercial induction appliances, espresso bars, or fitness equipment with no costly transformer upgrade.","green"],["Grease Interceptor: 1,500 Gallon","Existing exterior vault connection in place; reduces restaurant buildout lead time by approximately 6-8 weeks.","green"],["HVAC Capacity: 10-Ton RTU","Operational rooftop unit with manufacturer warranty; requires duct drop reconfiguration and diffuser balancing.","blue"]].map(([title,text,tone]) => <div key={title} className={`rounded border p-2 ${tone === "green" ? "border-[#BFE9D0] bg-[#F2FFF7]" : "border-[#C8DDF8] bg-[#F2F8FF]"}`}><p className={`text-[10px] font-medium ${tone === "green" ? "text-[#00A550]" : "text-[#2861E7]"}`}><CheckCircle2 className="mr-1 inline h-3 w-3" />{title}</p><p className="mt-2 text-[9px] leading-[12px] text-[#65758C]">{text}</p></div>)}</div></Panel> }
function Checklist({title,tone,items}:{title:string;tone:"green"|"orange";items:string[]}) { const Icon=tone === "green" ? CheckCircle2 : AlertTriangle; return <Panel><h3 className={`border-b pb-2 text-[11px] font-medium ${tone === "green" ? "text-[#00A550]" : "text-[#EE8300]"}`}>{title}</h3><ul className="mt-2 space-y-2">{items.map(item=><li key={item} className="flex gap-1.5 text-[9px] leading-[12px] text-[#65758C]"><Icon className={`mt-px h-3 w-3 shrink-0 ${tone === "green" ? "text-[#00A550]" : "text-[#EE8300]"}`}/><span>{item}</span></li>)}</ul></Panel> }
